name: Format and Lint

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - edited
      - reopened
    branches:
      - main

jobs:
  lint_and_format:
    name: Run ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v6
        with:
          node-version: '24.x'
          cache: pnpm
      - run: pnpm install
      - run: pnpm lint