name: CI & Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      package:
        description: 'Selecione o pacote para publicar'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - eslint-config
          - biome-config

jobs:
  lint_and_format:
    name: Lint and Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: '24.x'
          cache: pnpm
      - run: pnpm install
      - run: pnpm lint

  publish_eslint:
    name: Publish ESLint Config
    needs: lint_and_format
    if: github.event_name == 'workflow_dispatch' && (github.event.inputs.package == 'eslint-config' || github.event.inputs.package == 'all')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm
      - run: pnpm install
      - name: Publish ESLint Config
        run: pnpm --filter @m-p-toolkit/eslint-config publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  publish_biome:
    name: Publish Biome Config
    needs: lint_and_format
    if: github.event_name == 'workflow_dispatch' && (github.event.inputs.package == 'biome-config' || github.event.inputs.package == 'all')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v5
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org'
          cache: pnpm
      - run: pnpm install
      - name: Publish Biome Config
        run: pnpm --filter @m-p-toolkit/biome-config publish --no-git-checks --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
